### ISSUE TITLE
what is going on?

### ISSUE THREAD

**Issue by bobcolner** [wardowsmcc/badass#1]

**Comment by charlesj** [comment]
I came here from the changelog nightly.  If I had to guess, there is some kind of csrf that is getting people to star this repo, but I could be wrong.

**Comment by thedamian** [comment]
this is only for the bad ass developers. Everyone else can ignore this.

**Comment by charlesj** [comment]
What are ass developers and why is there a repository for those that are bad?  Is there going to be some sort of educational content uploaded to make them better ass developers?

**Comment by KepenJ** [comment]
WTF?

**Comment by joannesalfa** [comment]
Github introduced uploading files since the people do not know how to use Git

**Comment by neko** [comment]
warstrike pls

**Comment by 1994** [comment]
I also want to know

**Comment by Admol** [comment]
what ?

**Comment by MrTrvp** [comment]
How are you top stars? You don't even code..

**Comment by bhayes-dev** [comment]
wtb a code paying $1337.69

**Comment by xDragonZ** [comment]
______  _______  ______  _______  _______   _______
 |_____]  | _____ |  |          \  | _____ |   |______   |______
 |_____]  |            |  |_____/  |            |   ______|   ______|

**Comment by aprikyblue** [comment]
I heard there are ass trades here

**Comment by dbnoble** [comment]
I am become reddit

**Comment by wardowsmcc** [comment]
Funny how this turned out, looks like github needs to make updates :')

**Comment by raitucarp** [comment]
Open your eyes Bohemian Rhapsody
#10 opened an hour ago by nocarryr 
 3
No escape from reality
#9 opened an hour ago by dbnoble 
 0
Caught in a landslide
#8 opened an hour ago by nalancer08 
 0
Is this just fantasy?
#7 opened an hour ago by biohzrdmx 
 0
Is this the real life?
#6 opened an hour ago by webchimp 
 0
And you keep starring this repository?
#5 opened 6 hours ago by dikiaap 
 0
Why so many people to star this repo?
#4 opened 10 hours ago by kn007 
 9
What's wrong with the badass?
#3 opened 10 hours ago by ziming2018 
 0
what is going on?
#1 opened 13 hours ago by bobcolner 
 13
 ProTip! Notify someone on an issue with a mention, like: @raitucarp.
Status API Training Shop Blog About Pricing
© 2016 GitHub, Inc. Terms Privacy Security Contact Help
