### ISSUE TITLE
Why so many people to star this repo?

### ISSUE THREAD

**Issue by kn007** [wardowsmcc/badass#4]
I Wanna Know Why!

---------------------------
EDIT:
You are not badass you can't make advertising here.

**Comment by Akagi201** [comment]
+1

**Comment by sunfuze** [comment]
talk is cheap, just star + 1

**Comment by mcj2761358** [comment]
what happened?

**Comment by vishal052** [comment]
Just check out the secret.txt file uploaded directly from the git. Git now supports uploading files

**Comment by kn007** [comment]
@vishal052 Yes, I know this 9 hours ago. :)

**Comment by farooghkarimizadeh** [comment]
why people are staring and forking and watching this respo?why?

**Comment by yuzoxDD** [comment]
Clearly some mad 1337 hax are at play. If you look at a github 'dump' or hacked accounts list, you'll find a good few of the people starring have been hacked.

**Comment by ericoporto** [comment]
Ok, people in Github are really weird...

**Comment by Lin-H** [comment]
Totally. I won't star it.

**Comment by yuzoxDD** [comment]
It's OK guys. It was me, testing a script. The user who made the repo is a legit homosexual, do not hate.
