### ISSUE TITLE
Can I order pizza here?

### ISSUE THREAD

**Issue by dikiaap** [wardowsmcc/badass#41]
Need help with it.
I hope you give the best.

**Comment by wardowsmcc** [comment]
https://github.com/wardowsmcc/badass/blob/master/badass.pizza.jpg
Just prepared trial version for you, hope you enjoy this badass pizza.

**Comment by dikiaap** [comment]
wow, thanks man. look chinese or japanese pizza.

**Comment by wardowsmcc** [comment]
thanks badass brother, stay badass bro.

**Comment by dikiaap** [comment]
Ok, you is very badass. :+1: for you.
